export const domainsSeedData = [
  {
    slug: 'wedding',
    name: 'AI 婚纱照',
    description: '唯美婚纱、旅拍、中式喜庆，多风格一键生成',
    icon: 'Camera',
    color: 'from-pink-500 to-rose-500',
    cover_image:
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=800&auto=format&fit=crop',
    is_active: true,
    sort_order: 0,
    require_face_detection: true,
  },
  {
    slug: 'children',
    name: 'AI 儿童照',
    description: '百天、周岁、亲子合照，可爱风格随心选',
    icon: 'Baby',
    color: 'from-amber-400 to-orange-500',
    cover_image: null,
    is_active: true,
    sort_order: 1,
    require_face_detection: true,
  },
  {
    slug: 'id_photo',
    name: 'AI 证件照',
    description: '一键换底色，签证/简历/社保等规格齐全',
    icon: 'CreditCard',
    color: 'from-blue-500 to-indigo-500',
    cover_image: null,
    is_active: true,
    sort_order: 2,
    require_face_detection: true,
  },
  {
    slug: 'artistic',
    name: 'AI 艺术照',
    description: '油画、国风、赛博朋克，探索无限艺术风格',
    icon: 'Palette',
    color: 'from-purple-500 to-violet-500',
    cover_image: null,
    is_active: true,
    sort_order: 3,
    require_face_detection: false,
  },
  {
    slug: 'portrait',
    name: 'AI 个人写真',
    description: '形象照、社交头像、职场照，展现最佳状态',
    icon: 'User',
    color: 'from-teal-500 to-cyan-500',
    cover_image:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    is_active: true,
    sort_order: 4,
    require_face_detection: true,
  },
  {
    slug: 'anime',
    name: 'AI 动漫头像',
    description: '日漫、国漫、Q版风格，秒变二次元',
    icon: 'Wand2',
    color: 'from-fuchsia-500 to-pink-500',
    cover_image: null,
    is_active: true,
    sort_order: 5,
    require_face_detection: false,
  },
  {
    slug: 'maternity',
    name: 'AI 孕妇照',
    description: '记录孕期美好时光，专业孕妇写真',
    icon: 'Baby',
    color: 'from-pink-400 to-rose-400',
    cover_image: null,
    is_active: true,
    sort_order: 8,
    require_face_detection: true,
  },
  {
    slug: 'graduation',
    name: 'AI 毕业照',
    description: '毕业季纪念，学士服写真',
    icon: 'GraduationCap',
    color: 'from-blue-400 to-indigo-500',
    cover_image: null,
    is_active: true,
    sort_order: 9,
    require_face_detection: true,
  },
  {
    slug: 'couple',
    name: 'AI 情侣写真',
    description: '情侣合照，记录甜蜜时光',
    icon: 'Heart',
    color: 'from-rose-400 to-pink-500',
    cover_image: null,
    is_active: true,
    sort_order: 10,
    require_face_detection: true,
  },
];
